export const getAssignments = state => state.assignments
export const isLoginOpened = state => state.loginOpened
export const isSignupOpened = state => state.signupOpened
export const isEditOpened = state => state.editOpened
export const getUsername = state => state.username
export const getWarnings = state => state.warnings
export const modalTransitting = state => state.modalTransitting
export const getLoadingMsg = state => state.loadingMsg
export const getAssFilter = state => state.assFilter
